# Dynamic DockerFile application file for abcdesktopio generated by abcdesktopio/oc.apps/make.js
# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
ARG TAG=dev
FROM abcdesktopio/oc.template.gtk.18.04:$TAG
USER root
RUN apt-get update && apt-get install -y libgtk-3-0 libatk-bridge2.0-0 libx11-6 libxi6 libxxf86vm1 libxfixes3 libxrender1 libgl1 libnss3 qt5dxcb-plugin  wget libxss1 libasound2 libx11-xcb1 libxcb-dri3-0 libdrm2  libdrm-common libgbm1 libasound2-plugins libgail-common libgtk2.0-bin wget libcurl3 libxss1 && apt-get clean
RUN apt-get update && wget https://github.com/adobe/brackets/releases/download/release-1.14.1/Brackets.Release.1.14.1.64-bit.deb -O /tmp/bracket.deb && apt-get install -y /tmp/bracket.deb && rm /tmp/bracket.deb && rm -rf /var/lib/apt/lists/*
ENV BUSER balloon
LABEL oc.icon="brackets.svg"
LABEL oc.icondata="PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMjAiIGhlaWdodD0iMTIwIj4KICAgIDxkZWZzPgogICAgICAgIDxsaW5lYXJHcmFkaWVudCBpZD0iZnJhbWUiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIiB4MT0iNDMzLjUiIHkxPSItMTg1IiB4Mj0iNDMzLjUiIHkyPSItMjc3IiBncmFkaWVudFRyYW5zZm9ybT0ibWF0cml4KDEgMCAwIC0xIC0zNzMuNSAtMTc3KSI+CiAgICAgICAgICAgIDxzdG9wIG9mZnNldD0iMCIgc3RvcC1jb2xvcj0iIzI5YWJlMiIvPgogICAgICAgICAgICA8c3RvcCBvZmZzZXQ9IjAuNDc1NyIgc3RvcC1jb2xvcj0iIzI4YTllMSIvPgogICAgICAgICAgICA8c3RvcCBvZmZzZXQ9IjAuNjYzOSIgc3RvcC1jb2xvcj0iIzIzYTJkYyIvPgogICAgICAgICAgICA8c3RvcCBvZmZzZXQ9IjAuODAxMiIgc3RvcC1jb2xvcj0iIzFhOTZkNCIvPgogICAgICAgICAgICA8c3RvcCBvZmZzZXQ9IjAuOTEzIiBzdG9wLWNvbG9yPSIjMGU4NWM5Ii8+CiAgICAgICAgICAgIDxzdG9wIG9mZnNldD0iMSIgc3RvcC1jb2xvcj0iIzAwNzFiYyIvPgogICAgICAgIDwvbGluZWFyR3JhZGllbnQ+CiAgICAgICAgPGZpbHRlciBpZD0iYmx1ciIgeD0iLTEwIiB5PSItMTAiIHdpZHRoPSIxMiIgaGVpZ2h0PSIxMiI+CiAgICAgICAgICAgIDxmZUdhdXNzaWFuQmx1ciBpbj0iU291cmNlR3JhcGhpYyIgc3RkRGV2aWF0aW9uPSIxIi8+CiAgICAgICAgPC9maWx0ZXI+CiAgICA8L2RlZnM+CiAgICA8cmVjdCB4PSIxMCIgeT0iOSIgd2lkdGg9IjEwMCIgaGVpZ2h0PSIxMDAiIHJ4PSIyMCIgb3BhY2l0eT0iLjUiIGZpbHRlcj0idXJsKCNibHVyKSIvPgogICAgPHJlY3QgeD0iMTAiIHk9IjU4IiB3aWR0aD0iMTAwIiBoZWlnaHQ9IjUwIiByeD0iMjAiIGZpbGw9IiMxMTVhOTEiLz4KICAgIDxyZWN0IHg9IjEwIiB5PSI4IiB3aWR0aD0iMTAwIiBoZWlnaHQ9IjkyIiByeD0iMjAiIGZpbGw9InVybCgjZnJhbWUpIi8+CiAgICA8cmVjdCB4PSIyMiIgeT0iMjAiIHdpZHRoPSI3NiIgaGVpZ2h0PSI2OCIgcng9IjEwIiBmaWxsPSIjZmZmIi8+CiAgICA8cGF0aCBvcGFjaXR5PSIuNSIgZmlsdGVyPSJ1cmwoI2JsdXIpIiBkPSJNNTcsMjl2MTJINDN2MjZoMTR2MTNIMzBWMjlINTdNOTAsMjh2NTFINjNWNjdoMTVWNDFINjNWMjlIOTAiLz4KICAgIDxwYXRoIGZpbGw9IiM0ZDRkNGQiIGQ9Ik01NywyOHYxMkg0M3YyNmgxNHYxM0gzMFYyOEg1N005MCwyOHY1MUg2M1Y2NmgxNVY0MEg2M1YyOEg5MCIvPgo8L3N2Zz4="
LABEL oc.keyword="brackets,html,brackets"
LABEL oc.cat="utilities,office"
LABEL oc.desktopfile="brackets.desktop"
LABEL oc.launch="brackets.Brackets"
LABEL oc.template="abcdesktopio/oc.template.gtk.18.04"
ENV ARGS="--no-sandbox  --disable-gpu"
LABEL oc.name="Brackets"
LABEL oc.displayname="Brackets"
LABEL oc.path="/opt/brackets/Brackets"
LABEL oc.type=app
LABEL oc.rules="{\"homedir\":{\"default\":true}}"
LABEL oc.acl="{\"permit\":[\"all\"]}"
LABEL oc.host_config="{\"mem_limit\":\"512M\"}"
RUN  if [ -d /usr/share/icons ];   then cd /usr/share/icons;    /composer/safelinks.sh; fi 
RUN  if [ -d /usr/share/pixmaps ]; then cd /usr/share/pixmaps;  /composer/safelinks.sh; fi 
WORKDIR /home/balloon
USER balloon
ENV APPNAME "Brackets"
ENV APPBIN "/opt/brackets/Brackets"
LABEL oc.args="--no-sandbox  --disable-gpu"
ENV APP "/opt/brackets/Brackets"
