# Dynamic DockerFile application file for abcdesktopio generated by abcdesktopio/oc.apps/make.js
# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
ARG TAG=dev
FROM abcdesktopio/oc.template.gtk.firefox.rest:$TAG
COPY composer/init.d/init.firefox /composer/init.d/init.firefox
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y  -o Dpkg::Options::="--force-confold" firefox winbind && apt-get clean
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
ENV BUSER balloon
LABEL oc.icon="rest.svg"
LABEL oc.icondata="PHN2ZyB3aWR0aD0iMTI4IiBoZWlnaHQ9IjEyOCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KIDwhLS0gQ3JlYXRlZCB3aXRoIE1ldGhvZCBEcmF3IC0gaHR0cDovL2dpdGh1Yi5jb20vZHVvcGl4ZWwvTWV0aG9kLURyYXcvIC0tPgogPGc+CiAgPHRpdGxlPmJhY2tncm91bmQ8L3RpdGxlPgogIDxyZWN0IGZpbGw9IiNmZmYiIGlkPSJjYW52YXNfYmFja2dyb3VuZCIgaGVpZ2h0PSI0MDIiIHdpZHRoPSI1ODIiIHk9Ii0xIiB4PSItMSIvPgogPC9nPgogPGc+CiAgPHRpdGxlPkxheWVyIDE8L3RpdGxlPgogIDx0ZXh0IHN0eWxlPSJjdXJzb3I6IG1vdmU7IiBzdHJva2U9IiMwMDAiIHRyYW5zZm9ybT0ibWF0cml4KDEsMCwwLDMuMTE5OTM1NjQ0ODY5Mzk2NSwzLC05OS44NTk3OTIyNDgwNzkzNCkgIiB4bWw6c3BhY2U9InByZXNlcnZlIiB0ZXh0LWFuY2hvcj0ic3RhcnQiIGZvbnQtZmFtaWx5PSJIZWx2ZXRpY2EsIEFyaWFsLCBzYW5zLXNlcmlmIiBmb250LXNpemU9IjI0IiBpZD0ic3ZnXzEiIHk9IjU5LjUiIHg9IjE0IiBzdHJva2Utd2lkdGg9IjAiIGZpbGw9IiM1ZTAwYmMiPnsgUkVTVCB9PC90ZXh0PgogPC9nPgo8L3N2Zz4K"
LABEL oc.keyword="firefox,mozilla,web,internet"
LABEL oc.cat="development"
LABEL oc.desktopfile="firefox.desktop"
LABEL oc.launch="Navigator.Rest.Firefox"
LABEL oc.template="abcdesktopio/oc.template.gtk.firefox.rest"
ENV ARGS="--class=Rest.Firefox"
LABEL oc.name="FirefoxRest"
LABEL oc.displayname="Firefox-Rest"
LABEL oc.path="/usr/bin/firefox"
LABEL oc.type=app
LABEL oc.mimetype="text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;video/webm;application/x-xpinstall;"
LABEL oc.fileextensions="html;xml;gif"
LABEL oc.legacyfileextensions="html;xml"
RUN  if [ -d /usr/share/icons ];   then cd /usr/share/icons;    /composer/safelinks.sh; fi 
RUN  if [ -d /usr/share/pixmaps ]; then cd /usr/share/pixmaps;  /composer/safelinks.sh; fi 
WORKDIR /home/balloon
USER balloon
ENV APPNAME "FirefoxRest"
ENV APPBIN "/usr/bin/firefox"
LABEL oc.args="--class=Rest.Firefox"
ENV APP "/usr/bin/firefox"
