# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generateDockerFile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
 
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}
         
      - name: Use Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: "18.x"

      - name: Install dependencies
        run: npm install 
        
      - name: generate Dockerfile
        run: node make.js -r '3.0'

  generateInputDockerFile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
         
      - name: Generate matrix with all Dockerfiles of the repository
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(ls -l *.d | grep '^-' | awk -F ' ' '{print $9}' | jq -R -s -c 'split("\n") | map(select(length > 0))')"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      
  build:
    needs: generateInputDockerFile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.generateInputDockerFile.outputs.matrix) }}
    steps:
      - name: dump 
        run: |
          echo "Dockerfile=${{ matrix.path }}" 
          
      - name: "image"
        env: 
          image: ${{ matrix.path }}
        run: echo "image set to '${{ env.image }}'"
          
      - name: "image tag"
        env: 
          imagetag: debug${{ github.head_ref || github.ref_name || 'dev' }}
        run: echo "image tag set to '${{ env.imagetag }}'"
        
      - name: Build and push ${{ env.image }}:${{ env.imagetag }}
        uses: docker/build-push-action@v3
        with:
          file: ${{ env.image }}
          context: .
          platforms: linux/amd64, linux/arm64
          build-args: |
            TAG=3.0
          push: true
          tags: |
            abcdesktopio/${{ env.image }}:${{ env.imagetag }}


          
