# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generateInputDockerFile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate matrix with all Dockerfiles of the repository
        id: set-matrix
        run: |
          echo "::set-output name=matrix::$(ls -l *.d | grep '^-' | awk -F ' ' '{print $9}' | jq -R -s -c 'split("\n") | map(select(length > 0))')"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      
  build:
    needs: generateInputDockerFile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJson(needs.generateInputDockerFile.outputs.matrix) }}
    steps:
      - name: dump 
        run: |
          echo "dump" 
          echo "matrix ${{ matrix }}"
          echo "matrix.path ${{ matrix.path }}"
          echo "${{ matrix.inputPath }}"
          echo "end of dump" 
          
